version: '3.8'

services:
  businext_bot:
    image: businext:latest
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/usr/app/src
    command: npm run start:dev
