version: "3.8"

services:
  businext_bot:
    image: businext:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./src:/usr/app/src
    ports:
      - "4000:4000"
    command: npm run start:dev
