version: '3.8'

services:
  postgres:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=keystone
      - POSTGRES_PASSWORD=keystone
      - POSTGRES_DB=keystone
    ports:
      - '5432:5432'

  keystone:
    image: keystone:latest
    build:
      context: persistent-data-provider
    restart: unless-stopped
    env_file:
      - persistent-data-provider/.env
    ports:
      - '3000:3000'
    command: npm run dev
    depends_on:
      - postgres

  businext_bot:
    image: businext:latest
    build:
      context: .
      args:
        ENDPOINT_PORT: '${ENDPOINT_PORT:-4000}'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/usr/app/src
      - ./models:/usr/app/models
      - ./src/graphql/schema:/usr/app/lib/graphql/schema
    ports:
      - '${LOCAL_ENDPOINT_PORT:-4000}:${ENDPOINT_PORT:-4000}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: npm run start:dev
    depends_on:
      - keystone
